apiVersion: v1
kind: Service

metadata:
  name: securebank-service
  namespace: securebank

spec:
  selector:
    app: securebank

  type: LoadBalancer

  ports:
  - port: 80
    targetPort: 8080